#!/bin/zsh
#
#
# Modified from https://github.com/dustinkirkland/hollywood


mpcs=$(dirname $0:A)"/../share/mac_port_commands.sh"
source $mpcs

command -v man >/dev/null 2>&1 || exit 1

trap "pkill -f hollywood >/dev/null 2>&1; exit" INT

while true; do
	cmds=($(bash -c "compgen -c"))
	for cmd in $cmds; do
		man -P cat "$cmd" 
		sleep 0.1
	done
done
