#!/bin/zsh
#
#
# Modified from https://github.com/dustinkirkland/hollywood


mpcs=$(dirname $0:A)"/../share/mac_port_commands.sh"
source $mpcs

command -v stat >/dev/null 2>&1 || exit 1

trap "pkill -f hollywood >/dev/null 2>&1; exit" INT

while true; do
	for f in $(find /sys /dev 2>/dev/null | head -n 4096 | sort -R); do
		color=$(hollywood_colorize y)
		stat "$f"> >(sed $color>&1)
	done
done
